#!/bin/sh

pkill -u $UID -x polybar >/dev/null

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

for m in $(polybar --list-monitors | cut -d: -f1); do
  MONITOR=$m polybar --reload i3 &
done
