#!/bin/sh

RUNDIR="$HOME/.local/run/xob"

mkdir -p "$RUNDIR"

[ -n "$DISPLAY" ] || exit 1

INSTANCE="$RUNDIR/$DISPLAY"

mkdir -p "$INSTANCE"

if [ -e "$INSTANCE/pid" ]; then
  PID="$(<"$INSTANCE/pid")"
  if kill -0 "$PID"; then
    kill -9 "$PID"
  fi
  rm -f "$INSTANCE/pid"
fi

[ -e "$INSTANCE/pipe" ] && rm -f "$INSTANCE/pipe"

mkfifo "$INSTANCE/pipe"

(tail -f "$INSTANCE/pipe" | xob) &
echo $! > "$INSTANCE/pid"
