#!/bin/sh

STEP=5

usage() {
  echo "Usage: $0 [lower|raise|toggle]"
}

get_value() {
  local mute
  [ `pamixer --get-mute` = true ] && mute='!'
  printf '%.0f%s\n' "$(pamixer --get-volume)" "$mute"
}

if [ $# != 1 ]; then
  usage
  exit 1
fi

case "$1" in
  raise)
    pamixer -i "$STEP"
    ;;
  lower)
    pamixer -d "$STEP"
    ;;
  toggle)
    pamixer -t
    ;;
  *)
    usage
    exit 1
    ;;
esac

get_value

if [ -n "$WAYLAND_DISPLAY" ]; then
  [ -e "$HOME/.local/run/wob/$WAYLAND_DISPLAY/pipe" ] && \
    get_value > "$HOME/.local/run/wob/$WAYLAND_DISPLAY/pipe"
elif [ -n "$DISPLAY" ]; then
  [ -e "$HOME/.local/run/xob/$DISPLAY/pipe" ] && \
    get_value > "$HOME/.local/run/xob/$DISPLAY/pipe"
fi
